server:
  port: 8081

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

token:
  secret: lkajsbd8712631h23b