server:
  port: 8081

spring:
  config:
    import: optional:configserver:http://localhost:8082
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

token:
  secret: lkajsbd8712631h23b

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - info
