server:
  port: 8081

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: accountStatus
          uri: lb://apiaccountmanagement
          predicates:
            - Path=/**
            - Method=GET, POST, PUT, DELETE
        - id: usersStatus
          uri: lb://apiusers
          predicates:
            - Path=/**
            - Method=GET, POST, PUT, DELETE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
