server:
  port: 8082

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LukaszKk/SpringBootMicroservicesCloud/tree/main/ConfigServer
          username:
          password:
          clone-on-start: false
