server:
  port: 8082

spring:
  application:
    name: ConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:../SpringBootMicroservicesCloudConfig
        git:
          uri: https://github.com/LukaszKk/SpringBootMicroservicesCloudConfig
          default-label: master
          clone-on-start: false
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
          - refresh

encrypt:
  key: oakjshdkajhsd8712643jaldTYGFEkaje
  key-store:
    location: classpath:apiEncryptionKey.p12
    password: password
    type: pkcs12
    alias: apiEncryptionKey
