server:
  port: ${PORT:0}

spring:
  application:
    name: apiaccountmanagement
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
