server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: apiaccountmanagement
  devtools:
    restart:
      enabled: true
