server:
  port: ${PORT:0}

spring:
  config:
    import: optional:configserver:http://localhost:8082
  application:
    name: apiusers
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=LEGACY
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


hibernate:
  dialect: org.hibernate.dialect.H2Dialect

gateway:
  ip: 127.0.0.1

token:
  expiration-time: 86400000 # 24 hours
  secret: lkajsbd8712631h23b

login:
  url:
    path: /login # the same as default

logging:
  level:
    org:
      spring:
        service:
          AlbumsServiceClient: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      albums-ws:
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        minimumNumberOfCalls: 1
        eventConsumerBufferSize: 10