server:
  port: ${PORT:0}

spring:
  application:
    name: apiusers
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
