server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  config:
    import: optional:configserver:http://localhost:8082
  application:
    name: discoveryservice
